### PR TITLE
NET8 upgrade, updated NuGet packages and Node version

### PR DESCRIPTION
**Pull request by fabricioferreira**
- **Upgraded to NET8.**
- Updated all NuGet packages to their respective latest versions.
- Updated tasks.json to use Node20_1 as default, falling back to Node16 in case version 20.1 is not present.

### CODE REVIEW

**Comment by fabricioferreira** [comment]
@chwebdude this may require changes to the gh actions, but I don't seem to have access to change it.

**Comment by fabricioferreira** [comment]
Changes are required on the Azure DevOps pipeline, but I don't have access to do so. Would you be able to check that @chwebdude ? Thanks!

**Comment by chwebdude** [comment]
> Changes are required on the Azure DevOps pipeline, but I don't have access to do so. Would you be able to check that @chwebdude ? Thanks!

Thanks for the upgrade!
I switchted the pipeline definition to the new YAML oriented style. But the secrets to push to the marketplace are only available from builds from this repository, not from forks. Can you please push your code into this repo in a non-master branch?

**Comment by fabricioferreira** [comment]
Closed this PR as a new one has been raised.

**Pull request closed without merging**
